language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip
before_install:
  - if ! go get code.google.com/p/go.tools/cmd/cover code.google.com/p/go.tools/cmd/vet; then go get golang.org/x/tools/cmd/cover golang.org/x/tools/cmd/vet; fi
script: go run build.go
